deployment:
  tasks:
    - export DEPLOYPATH=/home/izdatels/public_html
    - /bin/rsync -av --exclude=".git" --exclude="node_modules" --exclude="vendor" ./ $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
